version: "3.9"

services:

  pg_db:
    container_name: d_database
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: D_DB
    ports:
      - 5432:5432
  app:
#    image: docker-spring-boot-postgres:latest
#    restart: always
    container_name: d_backend
    build: ./
    ports:
      - 8081:8080
    depends_on:
      - pg_db
    environment:
      DB_PORT: 5432
      DB_HOST: d_database
      DB_USER: postgres
      DB_PASS: 123
