spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/D_DB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    platform: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
          format_sql: true
    hibernate:
      #  ? Мы устанавливаем значение для обновления значения, чтобы в базе данных автоматически создавалась таблица,
      #  соответствующая определенной модели данных.
      ddl-auto: update
logging:
  level:
    root=debug:
#server:
#  port=8081:


