
spring:

  datasource:
    url: jdbc:postgresql://localhost:5400/D_DB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    platform: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
          format_sql: true
    hibernate:
#  ? Мы устанавливаем значение для обновления значения, чтобы в базе данных автоматически создавалась таблица,
#  соответствующая определенной модели данных.
      ddl-auto: update


